<?php

declare(strict_types=1);

namespace LVI\Tests;

use LVI\PassoDiTradvzione;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class TradvttoreCompostoTest extends TestCase
{
    private PassoDiTradvzione&MockObject $passo1, $passo2;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}